"""Add i18n JSONB fields for translations

Revision ID: 84513575bcb3
Revises: 8a77f2101348
Create Date: 2026-01-29 12:12:58.880374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84513575bcb3'
down_revision: Union[str, Sequence[str], None] = '8a77f2101348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exhibitions', sa.Column('title_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exhibitions', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('game_categories', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('safety_tools', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('safety_tools', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('zones', sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('zones', sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'description_i18n')
    op.drop_column('zones', 'name_i18n')
    op.drop_column('safety_tools', 'description_i18n')
    op.drop_column('safety_tools', 'name_i18n')
    op.drop_column('game_categories', 'name_i18n')
    op.drop_column('exhibitions', 'description_i18n')
    op.drop_column('exhibitions', 'title_i18n')
    # ### end Alembic commands ###
