"""Add session reporting fields

Revision ID: 8a77f2101348
Revises: a8323b30eb7f
Create Date: 2026-01-29 11:55:28.417951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a77f2101348'
down_revision: Union[str, Sequence[str], None] = 'a8323b30eb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_sessions', sa.Column('actual_player_count', sa.Integer(), nullable=True))
    op.add_column('game_sessions', sa.Column('table_condition', sa.String(length=20), nullable=True))
    op.add_column('game_sessions', sa.Column('end_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_sessions', 'end_notes')
    op.drop_column('game_sessions', 'table_condition')
    op.drop_column('game_sessions', 'actual_player_count')
    # ### end Alembic commands ###
