"""Add zones, physical_tables, rename game_tables to game_sessions

Revision ID: cef8a1899aac
Revises: ca3019a42edb
Create Date: 2026-01-26 11:01:40.202268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cef8a1899aac'
down_revision: Union[str, Sequence[str], None] = 'ca3019a42edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exhibition_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('delegated_to_group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['delegated_to_group_id'], ['user_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exhibition_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('physical_table_id', sa.UUID(), nullable=True),
    sa.Column('provided_by_group_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_players_count', sa.Integer(), nullable=False),
    sa.Column('safety_tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_accessible_disability', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gm_checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['physical_table_id'], ['physical_tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provided_by_group_id'], ['user_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Drop in correct order (respecting FK constraints)
    op.drop_table('table_participants')
    op.drop_table('game_tables')
    op.add_column('exhibitions', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='UTC'))
    op.add_column('exhibitions', sa.Column('grace_period_minutes', sa.Integer(), nullable=False, server_default='15'))
    op.add_column('time_slots', sa.Column('max_duration_minutes', sa.Integer(), nullable=False, server_default='240'))
    op.add_column('time_slots', sa.Column('buffer_time_minutes', sa.Integer(), nullable=False, server_default='15'))
    op.drop_column('time_slots', 'capacity_bonus')
    op.add_column('users', sa.Column('global_role', sa.String(length=20), nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'global_role')
    op.add_column('time_slots', sa.Column('capacity_bonus', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('time_slots', 'buffer_time_minutes')
    op.drop_column('time_slots', 'max_duration_minutes')
    op.drop_column('exhibitions', 'grace_period_minutes')
    op.drop_column('exhibitions', 'timezone')
    op.create_table('table_participants',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game_table_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_table_id'], ['game_tables.id'], name=op.f('table_participants_game_table_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('table_participants_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('table_participants_pkey'))
    )
    op.create_table('game_tables',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exhibition_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_slot_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provided_by_group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('min_age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_players_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('safety_tools', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_accessible_disability', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('game_tables_created_by_user_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], name=op.f('game_tables_exhibition_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('game_tables_game_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provided_by_group_id'], ['user_groups.id'], name=op.f('game_tables_provided_by_group_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], name=op.f('game_tables_time_slot_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('game_tables_pkey'))
    )
    op.drop_table('bookings')
    op.drop_table('game_sessions')
    op.drop_table('physical_tables')
    op.drop_table('zones')
    # ### end Alembic commands ###
