"""Add registration and language config to Exhibition

Revision ID: f6d350b3f7ac
Revises: 672bafad36f6
Create Date: 2026-01-29 09:36:04.267203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d350b3f7ac'
down_revision: Union[str, Sequence[str], None] = '672bafad36f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with server defaults for existing data
    op.add_column('exhibitions', sa.Column(
        'is_registration_open', sa.Boolean(), nullable=False, server_default='false'
    ))
    op.add_column('exhibitions', sa.Column(
        'registration_opens_at', sa.DateTime(timezone=True), nullable=True
    ))
    op.add_column('exhibitions', sa.Column(
        'registration_closes_at', sa.DateTime(timezone=True), nullable=True
    ))
    op.add_column('exhibitions', sa.Column(
        'primary_language', sa.String(length=10), nullable=False, server_default='en'
    ))
    op.add_column('exhibitions', sa.Column(
        'secondary_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exhibitions', 'secondary_languages')
    op.drop_column('exhibitions', 'primary_language')
    op.drop_column('exhibitions', 'registration_closes_at')
    op.drop_column('exhibitions', 'registration_opens_at')
    op.drop_column('exhibitions', 'is_registration_open')
    # ### end Alembic commands ###
